#!/usr/bin/env python3
"""
Interactive setup wizard for Migo Affiliate Workflows.
Run once to configure credentials and create config.yaml.
"""

import os
import shutil


def prompt(label: str, default: str = "") -> str:
    hint = f" [{default}]" if default else ""
    val = input(f"{label}{hint}: ").strip()
    return val or default


def main():
    print("\n" + "="*60)
    print("  Migo Affiliate Workflows — Setup Wizard")
    print("="*60)
    print("\nThis wizard will create your config.yaml file.\n")
    print("You'll need:")
    print("  1. Feishu App credentials (open.feishu.cn/app)")
    print("  2. Feishu Bot webhook URL (from a group chat → Settings → Bots)")
    print("  3. Your AFS Base app token (from the Bitable URL)\n")

    if os.path.exists("config.yaml"):
        overwrite = input("config.yaml already exists. Overwrite? (y/N): ").strip().lower()
        if overwrite != "y":
            print("Aborted.")
            return

    print("\n── Feishu App Credentials ──────────────────────────────")
    app_id = prompt("Feishu App ID (cli_xxx)")
    app_secret = prompt("Feishu App Secret")

    print("\n── Feishu Bot Webhook ──────────────────────────────────")
    webhook = prompt("Bot Webhook URL (https://open.feishu.cn/open-apis/bot/v2/hook/...)")

    print("\n── AFS Base Token ──────────────────────────────────────")
    print("  Tip: open your Bitable, copy the token from the URL")
    base_token = prompt("AFS Base App Token")

    print("\n── Table IDs (press Enter to skip and fill later) ──────")
    creator_pool = prompt("Creator Pool table ID", "tblREPLACE_creator_pool")
    video_table = prompt("Video Status table ID", "tblREPLACE_video_status")
    ls_table = prompt("LS Schedule table ID", "tblREPLACE_ls_schedule")
    campaign_table = prompt("Campaign Summary table ID", "tblREPLACE_campaign_summary")
    leads_table = prompt("Leads table ID", "tblREPLACE_leads")
    trend_table = prompt("Trend Data table ID", "tblREPLACE_trend")
    insight_table = prompt("Insights table ID", "tblREPLACE_insights")

    print("\n── Lead Qualification Thresholds ───────────────────────")
    min_followers = prompt("Min followers", "10000")
    min_gmv = prompt("Min GMV 30D (THB)", "500")
    min_eng = prompt("Min engagement rate (%)", "2.0")

    config = f"""# Migo Affiliate Workflows — Auto-generated by setup.py
# DO NOT commit this file to version control.

feishu_app_id: "{app_id}"
feishu_app_secret: "{app_secret}"
feishu_bot_webhook: "{webhook}"

afs_base_token: "{base_token}"

creator_pool_table_id: "{creator_pool}"
video_table_id: "{video_table}"
ls_schedule_table_id: "{ls_table}"
campaign_summary_table_id: "{campaign_table}"
leads_table_id: "{leads_table}"
trend_table_id: "{trend_table}"
insight_table_id: "{insight_table}"

lead_min_followers: {min_followers}
lead_min_gmv_30d: {min_gmv}
lead_min_engagement_rate: {min_eng}

timezone: "Asia/Bangkok"
default_campaign_id: "CAMP_JUN"
"""

    with open("config.yaml", "w") as f:
        f.write(config)

    print("\n✅ config.yaml created successfully!")
    print("\nNext steps:")
    print("  1. Install dependencies:  pip install -r requirements.txt")
    print("  2. Add TikTok CSV exports to:  data/samples/")
    print("  3. Test with dry run:  python run_workflow.py --workflow all --dry-run")
    print("  4. Run for real:       python run_workflow.py --workflow all")
    print("\nOr run a single workflow:  python run_workflow.py --workflow 1\n")


if __name__ == "__main__":
    main()
